version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
    deploy:
      replicas: 1

  account:
    image: ntu11022002/account:latest
    ports:
      - "5000:5000"
    volumes:
      - ./Account:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/account
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  notification:
    image: ntu11022002/notification:latest
    ports:
      - "5009:5009"
    volumes:
      - ./Notification:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/notification
      - PORT=5009
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - EMAIL_USER=nguyendinhtu11022002@gmail.com
      - EMAIL_PASS=dipotwokkbgjlryq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  chat:
    image: ntu11022002/chat:latest
    ports:
      - "5003:5003"
    volumes:
      - ./Chat:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/chat
      - PORT=5003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  order:
    image: ntu11022002/order:latest
    ports:
      - "5004:5004"
    volumes:
      - ./Order:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/order
      - PORT=5004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  payment:
    image: ntu11022002/payment:latest
    ports:
      - "5006:5006"
    volumes:
      - ./Payment:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/payment
      - PORT=5006
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VNP_TMN_CODE=BFOVPGBI
      - VNP_HASH_SECRET=JPJI1NRURNH39ZRZOWQYKJ3Q7GWL5302
      - VNP_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNP_RETURN_URL=http://localhost:3006/orderSuccess
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  product:
    image: ntu11022002/product:latest
    ports:
      - "5001:5001"
    volumes:
      - ./Product:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/product
      - PORT=5001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  review:
    image: ntu11022002/review:latest
    ports:
      - "5005:5005"
    volumes:
      - ./Review:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/review
      - PORT=5005
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2

  actions:
    image: ntu11022002/actions:latest
    ports:
      - "5007:5007"
    volumes:
      - ./Actions:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/actions
      - PORT=5007
    depends_on:
      - mongo
    networks:
      - my_network
    deploy:
      replicas: 2

  recommender:
    image: ntu11022002/recommender:latest
    ports:
      - "5008:5008"
    volumes:
      - ./Recommend:/app
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - my_network
    deploy:
      replicas: 2
  voucher:
    image: ntu11022002/voucher:latest
    ports:
      - "5010:5010"
    volumes:
      - ./Voucher:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/voucher
      - PORT=5010
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=9aFb3cH1iLp2sO8qR
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  shipping:
    image: ntu11022002/shipping:latest
    ports:
      - "5011:5011"
    volumes:
      - ./Shipping:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017/shipping
      - PORT=5011
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=9aFb3cH1iLp2sO8qR
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy   
  apigateway:
    image: ntu11022002/apigateway:latest
    ports:
      - "8000:8000"
    volumes:
      - ./ApiGateWay:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - account
      - order
      - payment
      - product
      - review
      - actions
      - chat
      - recommender
      - voucher
      - shipping
    networks:
      - my_network
    deploy:
      replicas: 2

volumes:
  mongo-data:
  redis-data:

networks:
  my_network:
    driver: overlay
