http:
  port: 6000
https:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  account:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/account*"
  product:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/product*"
  category:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/category*"
  order:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/order*"
  review:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/review*"
  payment:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/payment*"
  actions:
    methods: "GET,POST,PUT,DELETE"
    host: "*"
    paths: "/api/v1/actions*"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  accountService:
    url: "http://localhost:5000"
  productService:
    url: "http://localhost:5001"
  categoryService:
    url: "http://localhost:5002"
  orderService:
    url: "http://localhost:5004"
  reviewService:
    url: "http://localhost:5005"
  paymentService:
    url: "http://localhost:5006"    
  actionsService:
    url: "http://localhost:5007"    
policies:
  - basic-auth
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  bin:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  user:
    apiEndpoints:
      - account
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
      #       checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: accountService
  product:
    apiEndpoints:
      - product
    policies:
      # - jwt:
      #     action:
      #       secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
      #       checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: productService
  category:
    apiEndpoints:
      - category
    policies:
      - jwt:
          condition:
            name: method
            methods:
              - DELETE
              - POST
              - PUT
          action:
            secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
            checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: categoryService
  order:
    apiEndpoints:
      - order
    policies:
      - jwt:
          condition:
            name: method
            methods:
              - DELETE
              - POST
              - PUT
          action:
            secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
            checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: orderService
  review:
    apiEndpoints:
      - review
    policies:
      - jwt:
          condition:
            name: method
            methods:
              - DELETE
              - POST
              - PUT
          action:
            secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
            checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: reviewService
  payment:
    apiEndpoints:
      - payment
    policies:
      - jwt:
          condition:
            name: method
            methods:
              - DELETE
              - POST
              - PUT
          action:
            secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
            checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: paymentService
  actions:
    apiEndpoints:
      - actions
    policies:
      - jwt:
          condition:
            name: method
            methods:
              - DELETE
              - POST
              - PUT
          action:
            secretOrPublicKey: "9aFb3cH1iLp2sO8qR"
            checkCredentialExistence: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          action:
            headers:
              add:
                requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: actionsService
