http:
  port: 8000

https:
  port: 9876
  hostname: localhost

apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  account:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/account*"
  product:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/v1/product*"
        - "/api/v1/category*"
  voucher:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/voucher*"
  order:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/order*"
  review:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/review*"
  payment:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/payment*"
  actions:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/v1/actions*"
  recommender:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/v1/recommend*"
        - "/api/v1/metrics*"
  chat:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/*"
 
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  accountService:
    url: "http://account:5000"
  productService:
    url: "http://product:5001"
  voucherService:
    url: "http://voucher:5010"
  chatService:
    url: "http://chat:5003"
  orderService:
    url: "http://order:5004"
  reviewService:
    url: "http://review:5005"
  paymentService:
    url: "http://payment:5006"
  actionsService:
    url: "http://actions:5007"
  recommenderService:
    url: "http://recommender:5008"
policies:
  - cors
  - log
  - proxy
  - request-transformer
  - jwt

pipelines:
  bin:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  account:
    apiEndpoints:
      - account
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: accountService
  product:
    apiEndpoints:
      - product
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: productService
  voucher:
    apiEndpoints:
      - voucher
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: voucherService
  order:
    apiEndpoints:
      - order
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: orderService
  review:
    apiEndpoints:
      - review
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: reviewService
  payment:
    apiEndpoints:
      - payment
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: paymentService
  actions:
    apiEndpoints:
      - actions
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods: GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
              preflightContinue: false
              optionsSuccessStatus: 204
              #maxAge: 600
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: actionsService
  chat:
    apiEndpoints:
      - chat
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods: GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
              preflightContinue: false
              optionsSuccessStatus: 204
              #maxAge: 600
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: chatService
  recommender:
    apiEndpoints:
      - recommender
    policies:
      - cors:
          - action:
              origin: "*"
              credentials: true
              methods: GET,POST,PUT,DELETE,OPTIONS
              allowedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              exposedHeaders:
                [
                  "Content-type",
                  "Authorization",
                  "Origin",
                  "Access-Control-Allow-Origin",
                  "Accept",
                  "Options",
                ]
              #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
              preflightContinue: false
              optionsSuccessStatus: 204
              #maxAge: 600
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: recommenderService