version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "app.py"]

networks:
  default:
    name: my_network
